Repository kokonior/HTML-Projects, pull requests merged in 2021-10, with the labels that each got.

#1 yaelahaiz.html
  README.md
Labels: hacktoberfest-accepted

#2 Create Sandi L. Putra
  Sandi L. Putra
Labels: good first issue, hacktoberfest-accepted

#6 Create calculator.html
  calculator.html
Labels: good first issue, hacktoberfest-accepted

#5 Update README.md
  README.md
Labels: hacktoberfest-accepted

#7 Create calculator_rifqi.html
  calculator_rifqi.html
Labels: hacktoberfest-accepted, Create

#8 create RGBBackground.html
  RGBBackground.html
Labels: hacktoberfest-accepted, Create

#10 Create Sidebar.html
  Sidebar.html
Labels: hacktoberfest-accepted, Create

#11 Create konversi_aris.html
  konversi_aris.html
Labels: hacktoberfest-accepted, Create

#9 Create Landing Page
  Landing Page/img/Elon_Musk.png
  Landing Page/img/Logo.png
  Landing Page/index.html
  Landing Page/style.css
Labels: hacktoberfest-accepted, Create

#13 Create SurveyForm.html
  SurveyForm.html
Labels: hacktoberfest-accepted, Create

#12 Create formulir_aris
  formulir_aris
Labels: hacktoberfest-accepted, Create

#14 loginpage
  Login Page/images/logo.png
  Login Page/index.html
  Login Page/styles.css
Labels: hacktoberfest-accepted

#26 Create indexfarrel
  indexfarrel
Labels: hacktoberfest-accepted, Create

#23 Create calculate_aris.html
  calculate_aris.html
Labels: hacktoberfest-accepted, Create

#21 Create form_rifqi.html
  form_rifqi.html
Labels: hacktoberfest-accepted, Create

#20 Create html-video
  html-video
Labels: hacktoberfest-accepted, Create

#25 Added event page
  eventpage_tmahato.html
Labels: hacktoberfest-accepted

#24 add some page
  Covid-page/css/style.css
  Covid-page/img/corona-1.svg
  Covid-page/img/corona-2.svg
  Covid-page/img/header.png
  Covid-page/img/vaksin-1.svg
  Covid-page/img/vaksin-2.svg
  Covid-page/index.html
Labels: hacktoberfest-accepted

#27 Update and rename indexfarrel to indexfarrel.html
  indexfarrel
  indexfarrel.html
Labels: hacktoberfest-accepted

#22 add my project
  isallkun.html
Labels: good first issue, hacktoberfest-accepted

#19 Glassweb
  Glassweb/css/style.css
  Glassweb/glassweb1.html
Labels: enhancement, hacktoberfest-accepted

#18 add timeline html
  timeline.html
Labels: hacktoberfest-accepted

#17 Rename formulir_aris to formulir_aris.html
  formulir_aris.html
Labels: hacktoberfest-accepted

#15 Created landingPage.html
  landingPage.html
Labels: hacktoberfest-accepted, Create

#30 Create disable_all.js
  JavaScript/disable_all.js
Labels: hacktoberfest-accepted, Create

#29 Create alfin
  alfin
Labels: hacktoberfest-accepted, Create

#31 my code
  palindrome
Labels: hacktoberfest-accepted

#28 Update indexfarrel.html
  indexfarrel.html
Labels: enhancement, hacktoberfest-accepted

#35 Create yanuar_dark.html
  yanuar_dark.html
Labels: hacktoberfest-accepted, Create

#34 Create russss.html
  russss.html
Labels: hacktoberfest-accepted, Create

#36 Add a button
  .gitignore
  buttonHrishabh.html
Labels: enhancement, hacktoberfest-accepted

#33 Added portfolio page
  portfolio-page_tmahato.html
Labels: enhancement, hacktoberfest-accepted

#37 Create garlek123.html
  garlek123.html
Labels: hacktoberfest-accepted, Create

#39 change timeline html
  timeline.html
Labels: enhancement, hacktoberfest-accepted

#38 Create Shrijan26_clock.html
  Shrijan26_clock.html
Labels: hacktoberfest-accepted, Create

#41 Create How TO - Portfolio Gallery.html
  How TO - Portfolio Gallery.html
Labels: hacktoberfest-accepted, Create

#40 Create html-emoji.html
  html-emoji.html
Labels: hacktoberfest-accepted, Create

#44 add 404 page
  404Page/index.html
  404Page/script.js
  404Page/style.scss
Labels: enhancement, hacktoberfest-accepted

#43 update-paragraph
  Landing Page/index.html
Labels: hacktoberfest-accepted

#45 add project ahmadk-simple-todolist
  ahmadk-simple-todolist.html
Labels: enhancement, hacktoberfest-accepted

#47 added a new file for contact form
  contact-form.html
Labels: enhancement, hacktoberfest-accepted

#46 Added RandomCatsGenerator.html file
  RandomCatsGenerator.html
Labels: enhancement, hacktoberfest-accepted

#48 Added tiled info portfolio page
  TiledInfoPortfolio.html
Labels: enhancement, hacktoberfest-accepted

#51 partisipasi hacktoberfest2021
  ival.html
Labels: enhancement, hacktoberfest-accepted

#50 Added a HTML project
  project1.html
  project2.html
Labels: enhancement, hacktoberfest-accepted

#49 Create diamond.html
  diamond.html
Labels: hacktoberfest-accepted, Create

#53 Updated SurveyForm.html page by using Bootstrap 5
  SurveyForm.html
Labels: enhancement, hacktoberfest-accepted

#57 ayya2.html
  ayya2
Labels: enhancement, hacktoberfest-accepted

#56 A web page showing the animation(mini game)
  pragya-sharma11(web page)/index.html
  pragya-sharma11(web page)/script.js
  pragya-sharma11(web page)/style.css
Labels: hacktoberfest-accepted

#55 marco2.html
  marco2
Labels: enhancement, hacktoberfest-accepted

#58 PageOnDeserts
  DesertInfo/imgs/daniele-colucci-OtXJhYjbKeg-unsplash.jpg
  DesertInfo/imgs/des.jpg
  DesertInfo/imgs/icon.png
  DesertInfo/index.html
  DesertInfo/main.css
Labels: hacktoberfest-accepted

#59 Add new html template
  Simple Biodata/illus.png
  Simple Biodata/index.html
  Simple Biodata/style.css
Labels: enhancement, hacktoberfest-accepted

#64 add card with tailwind
  card-with-tailwind.html
Labels: enhancement, hacktoberfest-accepted

#63 Create yafsw
  yafsw
Labels: hacktoberfest-accepted, Create

#62 Update README.md
  README.md
Labels: hacktoberfest-accepted

#60 Add files via upload
  elbasrie-responsive.html
Labels: hacktoberfest-accepted

#69 Create iframevideo.html
  iframevideo.html
Labels: hacktoberfest-accepted, Create

#68 Update index.html
  Login Page/index.html
Labels: enhancement, hacktoberfest-accepted

#66 Update SurveyForm.html
  SurveyForm.html
Labels: enhancement, hacktoberfest-accepted

#65 Update yafsw
  yafsw
Labels: enhancement, hacktoberfest-accepted

#70 acc kak
  TemplateEmail_cp2940.html
Labels: hacktoberfest-accepted

#71 Create maintenance_page.html
  maintenance_page.html
Labels: hacktoberfest-accepted, Create

#72 Update calculator.html
  calculator.html
Labels: good first issue, hacktoberfest-accepted

#74 Project: To-do list added
  To-do list/index.html
  To-do list/styles.css
  To-do list/todo.js
Labels: hacktoberfest-accepted

#73 Update maintenance_page.html
  maintenance_page.html
Labels: hacktoberfest-accepted

#75 Update maintenance_page.html
  maintenance_page.html
Labels: enhancement, hacktoberfest-accepted

#78 Update maintenance_page.html
  maintenance_page.html
Labels: enhancement, hacktoberfest-accepted

#77 Added Simple Login Register Page
  Simple Login Register (Web Page with Dark Mode Toggle)/README.md
  Simple Login Register (Web Page with Dark Mode Toggle)/assets/images/moon-icon.png
  Simple Login Register (Web Page with Dark Mode Toggle)/assets/images/sun-icon.png
  Simple Login Register (Web Page with Dark Mode Toggle)/assets/style.css
  Simple Login Register (Web Page with Dark Mode Toggle)/demo.gif
  Simple Login Register (Web Page with Dark Mode Toggle)/index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#85 Memory Game
  Memory Game/images/1.jpg
  Memory Game/images/10.jpg
  Memory Game/images/11.jpg
  Memory Game/images/12.jpg
  Memory Game/images/13.jpg
  Memory Game/images/14.jpg
  Memory Game/images/15.jpg
  Memory Game/images/16.jpg
  Memory Game/images/17.jpg
  Memory Game/images/18.jpg
  Memory Game/images/19.jpg
  Memory Game/images/2.jpg
  Memory Game/images/20.jpg
  Memory Game/images/21.jpg
  Memory Game/images/22.jpg
  Memory Game/images/3.jpg
  Memory Game/images/4.jpg
  Memory Game/images/5.jpg
  Memory Game/images/6.jpg
  Memory Game/images/7.jpg
  Memory Game/images/8.jpg
  Memory Game/images/9.jpg
  Memory Game/index.html
  Memory Game/script.js
  Memory Game/style.css
Labels: good first issue, hacktoberfest-accepted

#84 added slider compare
  slider_compare/css/pixelcompare.css
  slider_compare/css/pixelcompare.min.css
  slider_compare/docs/_config.yml
  slider_compare/docs/index.html
  slider_compare/docs/landscape.jpg
  slider_compare/docs/landscape_bw.jpg
  slider_compare/docs/style.css
  slider_compare/js/pixelcompare.js
  slider_compare/js/pixelcompare.min.js
Labels: hacktoberfest-accepted

#83 added my `LinkTreeClone` project
  LinkTreeClone/favicon.ico
  LinkTreeClone/index.html
  LinkTreeClone/logo.png
  LinkTreeClone/style.css
Labels: hacktoberfest-accepted

#82 survey inggris
  surveyenggres.html
Labels: hacktoberfest-accepted

#81 EktraLogin
  EktraLogin
Labels: hacktoberfest-accepted

#80 Retro style text template
  Hello_world_retro/index.html
  Hello_world_retro/style.css
Labels: hacktoberfest-accepted

#86 taufiqhida
  taufiqhida
Labels: hacktoberfest-accepted

#90 EktraLogin
  EktraLogin
Labels: hacktoberfest-accepted

#89 alakadutz
  alakadutz
Labels: enhancement, hacktoberfest-accepted

#88 Update SurveyForm.html
  SurveyForm.html
Labels: enhancement, hacktoberfest-accepted

#87 Created pasindujr-loremipsum-generator.html
  pasindujr-loremipsum-generator.html
Labels: hacktoberfest-accepted

#91 Create maintenance_page_2.html
  maintenance_page_2.html
Labels: hacktoberfest-accepted, Create

#94 add a suit game
  suitGame/asset/batu.png
  suitGame/asset/gunting.png
  suitGame/asset/kertas.png
  suitGame/asset/logo.png
  suitGame/asset/refresh.png
  suitGame/css/style.css
  suitGame/index.html
  suitGame/js/script.js
Labels: hacktoberfest-accepted

#93 Update maintenance_page_2.html
  maintenance_page_2.html
Labels: hacktoberfest-accepted

#92 blog page design in html and CSS
  blog-page/blog.html
  blog-page/image/1.jpg
  blog-page/image/b1.jpg
  blog-page/image/b2.jpg
  blog-page/image/b3.jpg
  blog-page/image/b4.jpg
  blog-page/image/b5.jpg
  blog-page/image/b6.jpg
  blog-page/image/bl1.jpg
  blog-page/image/bl2.jpg
  blog-page/image/bl3.jpg
  blog-page/image/fgf.jpg
  blog-page/image/head-baner.jpg
  blog-page/image/logo.png
  blog-page/image/sdffs.jpg
  blog-page/image/wave.png
  blog-page/style.css
Labels: hacktoberfest-accepted

#96 Create gradationColors.html
  gradationColors.html
Labels: hacktoberfest-accepted, Create

#95 Update maintenance_page_2.html
  maintenance_page_2.html
Labels: enhancement, hacktoberfest-accepted

#97 registratinForm
  registratinForm.html
Labels: hacktoberfest-accepted

#98 alakadutz
  web
Labels: hacktoberfest-accepted

#99 Update maintenance_page_2.html
  maintenance_page_2.html
Labels: enhancement, hacktoberfest-accepted

#103 Update EktraLogin
  EktraLogin
Labels: hacktoberfest-accepted

#101 Create ecom
  ecom
Labels: hacktoberfest-accepted, Create

#100 Create center-of-the-page.html
  center-of-the-page.html
Labels: hacktoberfest-accepted, Create

#106 Update SurveyForm.html
  SurveyForm.html
Labels: hacktoberfest-accepted

#105 Tetris game added
  Tetris-Game/tetris.html
Labels: hacktoberfest-accepted

#104 pomodoro
  pomodoro/README.md
  pomodoro/favicon.ico
  pomodoro/index.html
  pomodoro/notification.mp3
  pomodoro/scripts.js
  pomodoro/styles.css
Labels: hacktoberfest-accepted

#107 Create DMuhammad
  DMuhammad
Labels: hacktoberfest-accepted

#108 Create kurir
  kurir
Labels: hacktoberfest-accepted, Create

#110 Create basicHackToberFest
  basicHackToberFest
Labels: hacktoberfest-accepted, Create

#287 added a simple blood bank project
  Blood Bank Project/firebase-debug.log
  Blood Bank Project/images/donate-blood.jpg
  Blood Bank Project/images/home1.jpg
  Blood Bank Project/images/home2.PNG
  Blood Bank Project/images/images.jpg
  Blood Bank Project/images/logo.png
  Blood Bank Project/index.html
  Blood Bank Project/pages/donor.html
  Blood Bank Project/pages/donorprofile.html
  Blood Bank Project/pages/edit.html
  Blood Bank Project/pages/index.html
  Blood Bank Project/pages/login.html
  Blood Bank Project/pages/myprofile.html
  Blood Bank Project/pages/signup.html
  Blood Bank Project/pages/styles.css
Labels: hacktoberfest-accepted

#286 Add github commit contribution example
  github-commit-contribution.html
Labels: hacktoberfest-accepted

#284 add google search page clone
  Google-clone/9square.png
  Google-clone/index.html
  Google-clone/logogoogle.png
  Google-clone/style.css
Labels: hacktoberfest-accepted

#285 Add 3D cube effect
  3d-cube-effect/index.html
  3d-cube-effect/spruce_log.png
  3d-cube-effect/spruce_log_top.png
Labels: hacktoberfest-accepted

#283 Add styling input example
  input-styling.html
Labels: hacktoberfest-accepted

#282 Add simon-game.html
  simon-game.html
Labels: hacktoberfest-accepted

#293 uPDATE
  TiledInfoPortfolio.html
Labels: hacktoberfest-accepted

#292 Update table
  table.html
Labels: hacktoberfest-accepted

#291 Hacktober
  biodata
Labels: hacktoberfest-accepted

#290 Created a new file
  Survey Form/Survey.html
Labels: hacktoberfest-accepted

#289 created a new file
  Animated Homepage
Labels: hacktoberfest-accepted

#288 add btc near realtime chart
  btc-charts/index.html
  btc-charts/script.js
  btc-charts/style.css
Labels: hacktoberfest-accepted
